name: ceat_dealer_portal
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+2

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^0.13.3
  intl: ^0.18.0
  animated_text_kit: ^4.2.1
  motion: ^2.0.1
  flutter_animate: ^4.5.2
  rive: ^0.9.0
  shared_preferences: ^2.0.6
  convert: ^3.1.2
  flutter_launcher_icons: ^0.13.1 
  
  table_calendar: ^3.0.0
  pdf: ^3.6.0
  printing: ^5.0.0
  path_provider: ^2.0.11
  permission_handler: ^11.3.1
  device_info_plus: ^11.2.0
  open_filex: ^4.7.0
  dropdown_search: ^5.0.6
  url_launcher: ^6.3.1
  image_picker: ^1.0.4
  mime: ^2.0.0
  flutter_pdfview: ^1.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/ceat-logo-present-scaled.png
    - assets/images/profile.jpg
    - assets/images/ceat-logo-present-scaled.png
    - lib/uploads/TRADE-COMMUNICATION-LETTER.pdf
    - lib/uploads/TRADE-COMUNICATION.pdf
    - lib/uploads/CEAT-RETAIL-PRICE.pdf
    - assets/uploads/Guidelines-for-Taking-Photos.pdf

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/ceat.png"  # Path to your icon
  adaptive_icon_background: "#0047AB"  # (Optional) Adaptive icon background
  min_sdk_android: 21